version: "3.9"

services:
  rustapp:
    container_name: rustapp
    image: niklasalbinsson/auth-endpoint:1.0.0
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DATABASE_URL: postgres://myuser:mypassword@db:5432/mydatabase
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:15-alpine
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
